variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1
  GIT_CLEAN_FLAGS: -f

image: "liuchong/rustup:nightly"

stages:
  - check

# Setup qemu, nightly compiler and cargo tools
before_script:
    - apt-get update
    - rustup component add rust-src llvm-tools-preview
    - cargo install bootimage cargo-xbuild cargo-make
    - rustc --version && cargo --version

check-x86_64:
  stage: check
  cache:
    key: "cache-linux"
    paths:
        - ./target
  script:
    - apt-get install -yqq --no-install-recommends qemu-system-x86
    - cargo xclippy --target "targets/x86_64-hakkero.json"
    - cargo xtest --target "targets/x86_64-hakkero.json"

check-aarch64:
  stage: check
  cache:
    key: "cache-linux"
    paths:
        - ./target
  script:
    - apt-get install -yqq --no-install-recommends qemu-system-arm
    - RUST_FLAGS="-Z macro-backtrace -C board=\"virt\"" cargo xclippy --target "targets/aarch64-hakkero.json"
