variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch
  GIT_DEPTH: 1
  GIT_CLEAN_FLAGS: -f

image: "liuchong/rustup:nightly"

stages:
  - check

# Setup qemu, nightly compiler and cargo tools
before_script:
    - apt-get update && apt-get install -yqq --no-install-recommends qemu-system-x86
    - rustup component add rust-src llvm-tools-preview
    - cargo install bootimage cargo-xbuild
    - rustc --version && cargo --version

check:
  stage: check
  cache:
    key: "cache-linux"
    paths:
        - ./target
  script:
    - cargo xcheck --verbose

test:
  stage: check
  cache:
    key: "cache-linux"
    paths:
        - ./target
  script:
    - cargo xtest --all --verbose

clippy:
  stage: check
  cache:
    key: "cache-linux"
    paths:
        - ./target
  script:
    - cargo xclippy --verbose
